version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-net
    user: root # Often needed to access docker socket inside container

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - devops-net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
      - "8082:8082" # Exposed for Docker Registry Connector later
    volumes:
      - nexus-data:/nexus-data
    networks:
      - devops-net

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: annotation_app_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - devops-net

networks:
  devops-net:
    driver: bridge

volumes:
  jenkins_home:
  nexus-data:
